services:
  api:
    build: .
    container_name: spe_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - spe_data:/app/uploads
    environment:
      - PROJECT_NAME=SPE
      - TIMEZONE=America/Fortaleza
      - SQLALCHEMY_DATABASE_URI=sqlite:///./spe.db
    restart: unless-stopped

volumes:
  spe_data: