services:
  api:
    build: .
    container_name: spe_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - TIMEZONE=${TIMEZONE}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    restart: unless-stopped